### PR TITLE
fix header issue when user makes edit in food history tab

### PR DESCRIPTION
**Pull request by tanzil7**

### CODE REVIEW

**Review by JustinParkCS — COMMENTED** [review]
after making the changes to this API, have you checked other pages which uses this API??
for example the track page: nutrition tracker tab uses this.

**Comment by tanzil7** [comment]
> after making the changes to this API, have you checked other pages which uses this API?? for example the track page: nutrition tracker tab uses this.

yes, I checked the nutrient tracker tab and it works. I added food from the API search and checked the nutrient tracker updates and it does.

**Comment by JustinParkCS** [comment]
Sorry, i mistook the code... I thought you had adjusted one of the parameters.

**Review by JustinParkCS — APPROVED** [review]

**Comment by tanzil7** [comment]
> Sorry, i mistook the code... I thought you had adjusted one of the parameters.

no worries. yes it looked like i did change the parameters but i didnt. it just that when i save the page it automatically fixes the code.

**Pull request merged**
